In [2]:
import numpy as np

### 기본 슬라이싱

In [6]:
ndarray = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print("ndarray[2:5]:", ndarray[2:5])
print("ndarray[-3:]:", ndarray[-3:])
print("ndarray[1:7:2]:", ndarray[1:7:2])
print("ndarray[::-1]:", ndarray[::-1])

ndarray[2:5]: [2 3 4]
ndarray[-3:]: [7 8 9]
ndarray[1:7:2]: [1 3 5]
ndarray[::-1]: [9 8 7 6 5 4 3 2 1 0]


In [3]:
ndarray = np.array(
    [[0, 10, 20, 30],
     [1, 11, 21, 31],
     [2, 12, 22, 32],
     [3, 13, 23, 33],
     [4, 14, 24, 34],
     [5, 15, 25, 35],
     [6, 16, 26, 36],
     [7, 17, 27, 37],
     [8, 18, 28, 38],
     [9, 19, 29, 39]]
)

# 80%의 행과 20%의 행을 선택
train_dataset = ndarray[0:int(len(ndarray)*0.8)]
test_dataset = ndarray[int(len(ndarray)*0.8):len(ndarray)]
print(train_dataset, "\n")
print(test_dataset, "\n")

[[ 0 10 20 30]
 [ 1 11 21 31]
 [ 2 12 22 32]
 [ 3 13 23 33]
 [ 4 14 24 34]
 [ 5 15 25 35]
 [ 6 16 26 36]
 [ 7 17 27 37]] 

[[ 8 18 28 38]
 [ 9 19 29 39]] 



In [8]:
ndarray = np.array(
    [[0, 10, 20, 30],
     [1, 11, 21, 31],
     [2, 12, 22, 32],
     [3, 13, 23, 33],
     [4, 14, 24, 34],
     [5, 15, 25, 35],
     [6, 16, 26, 36],
     [7, 17, 27, 37],
     [8, 18, 28, 38],
     [9, 19, 29, 39]]
)

# 처음 8개 행과 모들 열을 선택
print(ndarray[0:8, :]) # ndarray[0:8]과 동일
print()

# 처음 8개 행을 가져오되 2번 열부터 끝까지 선택
print(ndarray[0:8, 2:])

[[ 0 10 20 30]
 [ 1 11 21 31]
 [ 2 12 22 32]
 [ 3 13 23 33]
 [ 4 14 24 34]
 [ 5 15 25 35]
 [ 6 16 26 36]
 [ 7 17 27 37]]

[[20 30]
 [21 31]
 [22 32]
 [23 33]
 [24 34]
 [25 35]
 [26 36]
 [27 37]]


인덱싱과 슬라싱의 결합

In [ ]:
ndarray = np.array(
    [[0, 10, 20, 30],
     [1, 11, 21, 31],
     [2, 12, 22, 32],
     [3, 13, 23, 33],
     [4, 14, 24, 34],
     [5, 15, 25, 35]]
)

# 0축의 인덱스가 3의 배수인 것을 인덱싱 + 1축의 1:3 요소 슬라이싱
result = ndarray[
            np.array([i for i in range(ndarray.shape[0]) if i%3==0]), 
            1:3
        ]
print(result)


[[10 20]
 [13 23]]
