In [1]:
# 랜덤 값 생성 및 넘파이 배열 처리를 위한 라이브러리 임포트
import random
import numpy as np

# 2일 동안의 온도 데이터를 저장할 리스트 (최종적으로 3D 배열가 됨)
days_temp = []

# 외부 루프: 2일 동안 반복
for day in range(2):
    # 하루 동안의 온도 데이터를 저장할 리스트 (2D 배열이 됨)
    day_temp = []
    
    # 내부 루프: 0시부터 23시까지 4시간 간격으로 반복 (0, 4, 8, 12, 16, 20시)
    # 하루에 총 6번 측정
    for hour in range(0, 24, 4):
        # 현재 온도를 15~25도 사이의 랜덤 값으로 생성
        curr_temp = random.randint(15, 25)
        
        # 이전 4시간 동안의 최고 온도 (예제에서는 고정값 25도)
        max_temp = 25
        
        # 이전 4시간 동안의 최저 온도 (예제에서는 고정값 15도)
        min_temp = 15
        
        # 이전 4시간 동안의 평균 온도 계산
        mean_temp = int((max_temp+min_temp)/2)
        
        # 한 시간대의 온도 정보를 리스트로 구성 (1D 배열)
        # [현재온도, 최고온도, 최저온도, 평균온도]
        temperature = [curr_temp, max_temp, min_temp, mean_temp]
        
        # 하루 데이터에 추가
        day_temp.append(temperature)
    
    # 2일 데이터에 하루치 데이터 추가
    days_temp.append(day_temp)

# 리스트를 넘파이 3D 배열로 변환
# 형태: (2일, 6번 측정, 4개 온도값) = (2, 6, 4)
dataset = np.array(days_temp)

# 배열의 차원 정보 출력
print(dataset)
print(f"배열 형태: {dataset.ndim}D, {dataset.shape}")  # 3D, (2, 6, 4)
print(f"측정 일수: {dataset.shape[0]}")  # 2일
print(f"측정 주기: {dataset.shape[1]}")  # 하루에 6번 (4시간 간격)
print(f"측정 값수: {dataset.shape[2]}")  # 각 측정마다 4개의 값

[[[15 25 15 20]
  [18 25 15 20]
  [17 25 15 20]
  [17 25 15 20]
  [23 25 15 20]
  [25 25 15 20]]

 [[17 25 15 20]
  [18 25 15 20]
  [25 25 15 20]
  [24 25 15 20]
  [25 25 15 20]
  [24 25 15 20]]]
배열 형태: 3D, (2, 6, 4)
측정 일수: 2
측정 주기: 6
측정 값수: 4
