In [1]:
import numpy as np  # 넘파이 라이브러리 임포트

### 생성 함수

In [ ]:
# 2중 리스트 생성
data = [[1, 2], 
        [3, 4]]

# 리스트를 넘파이 배열로 변환
ndarray1 = np.array(data)

# ndarray1을 독립적으로 복사
ndarray2 = np.copy(ndarray1)

# ndarray2의 첫 번째 요소 값 변경
ndarray2[0, 0] = 10

# 원본 배열 출력 (값 변경 없음)
print(ndarray1)

# 복사한 배열 출력 (값 변경)
print(ndarray2)

[[1 2]
 [3 4]]
[[10  2]
 [ 3  4]]


In [4]:
import numpy as np  # 넘파이 라이브러리 임포트

# 0으로 채워진 2x3 배열 생성
ndarray = np.zeros((2, 3))
print(ndarray)
print()

# 1로 채워진 2x3 배열 생성
ndarray = np.ones((2, 3))
print(ndarray)
print()

# 0과 1 사이의 균등 분포 난수로 채워진 2x3 배열 생성
ndarray = np.random.rand(2, 3)
print(ndarray)
print()

# 표준 정규 분포(평균=0, 표준편차=1) 난수로 채워진 2x3 배열 생성
ndarray = np.random.randn(2, 3)
# ndarray = np.random.normal(0, 1, (2, 3))  # 동일한 결과
print(ndarray)
print()

# 0 이상 256 미만의 정수 난수로 채워진 2x3 배열 생성
ndarray = np.random.randint(0, 256, size=(2, 3))
print(ndarray)
print()

# 0부터 11 미만까지 2씩 증가하는 1차원 배열 생성 [0, 2, 4, 6, 8, 10]
ndarray = np.arange(0, 11, 2)
print(ndarray)


[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[0.14630869 0.55720223 0.92728639]
 [0.6271863  0.88668189 0.96832372]]

[[ 0.30286912  0.50213176  0.65539951]
 [-1.17719832  0.12261071 -0.37238846]]

[[139 180 171]
 [ 93 248 159]]

[ 0  2  4  6  8 10]


### 형태 변경 함수

In [5]:
ndarray1 = np.array(
    [[[1, 2, 3], 
      [3, 4, 5]]]
)
print(ndarray1, ndarray1.shape)
print()

# reshape 함수 사용해서 배열 형태 변경
ndarray2 = np.reshape(ndarray1, (1, 3, 2))
print(ndarray2, ndarray2.shape)
print()

# -1을 사용해서 자동 계산
ndarray3 = np.arange(120)
ndarray4 = np.reshape(ndarray3, (4, -1))   # (4, 30)
print(ndarray4.shape)


[[[1 2 3]
  [3 4 5]]] (1, 2, 3)

[[[1 2]
  [3 3]
  [4 5]]] (1, 3, 2)

(4, 30)


In [6]:
ndarray1 = np.array(
    [[[1, 2, 3], 
      [3, 4, 5]]]
)

print(ndarray1, ndarray1.shape)
print()

# 방법1: 인덱싱 문법을 이용해서 np.newaxis를 0축으로 추가
ndarray2 = ndarray1[np.newaxis, ...]

# 방법2: expand_dims 함수 사용해서 0축 추가
# ndarray2 = np.expand_dims(ndarray1, axis=0)

# 방법3: reshape 함수 사용해서 0축 추가
# ndarray2 = np.reshape(ndarray1, (1, 1, 2, 3))

print(ndarray2, ndarray2.shape)

[[[1 2 3]
  [3 4 5]]] (1, 2, 3)

[[[[1 2 3]
   [3 4 5]]]] (1, 1, 2, 3)


In [7]:
ndarray1 = np.array(
    [[[1, 2, 3], 
      [3, 4, 5]]]
)

print(ndarray1, ndarray1.shape)
print()

# 방법1: np.newaxis 사용해서 마지막 축에 추가
ndarray2 = ndarray1[..., np.newaxis]

# 방법2: expand_dims 함수 사용해서 마지막 축에 추가
# ndarray2 = np.expand_dims(ndarray1, axis=-1)

# 방법3: reshape 함수 사용해서 마지막 축에 추가
# ndarray2 = np.reshape(ndarray1, (1, 2, 3, 1))

print(ndarray2, ndarray2.shape)


[[[1 2 3]
  [3 4 5]]] (1, 2, 3)

[[[[1]
   [2]
   [3]]

  [[3]
   [4]
   [5]]]] (1, 2, 3, 1)


In [9]:
ndarray1 = np.array(
    [[[1, 2, 3], 
      [3, 4, 5]]]
)
print(ndarray1, ndarray1.shape)
print()

# 방법1: flatten 함수 사용해서 1D로 변경
ndarray2 = ndarray1.flatten()

# 방법2: reshape 함수 사용해서 1D로 변경
# ndarray2 = np.reshape(ndarray1, (6,))

print(ndarray2, ndarray2.shape)


[[[1 2 3]
  [3 4 5]]] (1, 2, 3)

[1 2 3 3 4 5] (6,)


In [10]:
ndarray1 = np.array(
    [[[1, 2, 3], 
      [3, 4, 5]]]
)

print(ndarray1, ndarray1.shape)
print()

# 1축 제거
ndarray2 = np.squeeze(ndarray1)
print(ndarray2, ndarray2.shape)


[[[1 2 3]
  [3 4 5]]] (1, 2, 3)

[[1 2 3]
 [3 4 5]] (2, 3)


### 요소 추가/제거 함수

In [9]:
ndarray = np.array(
    [[1, 1], 
     [3, 3]]
)

# 0축의 0 인덱스 위치에 [0, 0] 추가
ndarray = np.insert(ndarray, 0, np.array([0, 0]), axis=0)
print(ndarray, ndarray.shape)
print()

# 0축의 2 인덱스 위치에 [2, 2] 추가
ndarray = np.insert(ndarray, 2, [2, 2], axis=0)
print(ndarray, ndarray.shape)

[[0 0]
 [1 1]
 [3 3]] (3, 2)

[[0 0]
 [1 1]
 [2 2]
 [3 3]] (4, 2)


In [12]:
ndarray = np.array(
    [[1, 1], 
     [2, 2]]
)

# 0축의 맨끝에 [3, 3] 추가
ndarray = np.append(ndarray, np.array([[3, 3]]), axis=0)
print(ndarray, ndarray.shape)

[[1 1]
 [2 2]
 [3 3]] (3, 2)


In [13]:
ndarray = np.array(
    [[1, 1], 
     [2, 2], 
     [3, 3]]
)

# 0축의 1 인덱스 위치에 있는 요소 제거
ndarray = np.delete(ndarray, 1, axis=0)
print(ndarray, ndarray.shape)


[[1 1]
 [3 3]] (2, 2)


### 요소 섞기 함수

In [14]:
dataset = np.array(
    [[1, 11, 21, 31],
     [2, 12, 22, 32],
     [3, 13, 23, 33],
     [4, 14, 24, 34],
     [5, 15, 25, 35]]
)

# 복사본 생성
dataset_cloned = np.copy(dataset)

# 0축을 기준으로 행 단위로 섞기 
np.random.shuffle(dataset_cloned)

print(dataset)
print()
print(dataset_cloned)


[[ 1 11 21 31]
 [ 2 12 22 32]
 [ 3 13 23 33]
 [ 4 14 24 34]
 [ 5 15 25 35]]

[[ 2 12 22 32]
 [ 5 15 25 35]
 [ 4 14 24 34]
 [ 1 11 21 31]
 [ 3 13 23 33]]


### 요소 검색 함수

In [ ]:
ndarray = np.array([0.1, 0.5, 0.3, 0.9, 0.2])

# 사례: 분류 모델의 출력값(확률분포)에서 가장 큰 값의 인덱스를 찾기
max_index = np.argmax(ndarray)
print(f"max_index: {max_index}, max_value: {ndarray[max_index]}")

min_index = np.argmin(ndarray)
print(f"min_index: {min_index}, min_value: {ndarray[min_index]}")

max_index: 3, max_value: 0.9
min_index: 0, min_value: 0.1


In [16]:
print(np.count_nonzero([1, 0, 3, 0, 5]))
print(np.count_nonzero([True, False, True]))

3
2


In [18]:
ndarray = np.array([[1, 1, 1], 
                    [2, 2, 0], 
                    [3, 3, 3]])

# 결측값이 있는 샘플 수를 얻는 방법1
non_zero_counts = np.count_nonzero(ndarray, axis=1)
non_zero_counts


array([3, 2, 3])

In [20]:
samples_with_zero = np.count_nonzero(non_zero_counts != ndarray.shape[1])
print("결측값이 있는 샘플 수:", samples_with_zero)
samples_with_zero


결측값이 있는 샘플 수: 1


np.int64(1)

In [ ]:
# 배열 원소에서 결측치의 개수를 세는 방법
ndarray = np.array([[1, 1, 1], 
                    [2, 2, 0], 
                    [3, 3, 3]])

# 결측값이 있는 샘플 수를 얻는 방법2
# np.any(): 하나라도 0이 있는 경우 True 반환
any_result = np.any(ndarray == 0, axis=1)
print(any_result)

rows_with_zero = np.count_nonzero(np.any(ndarray == 0, axis=1))
rows_with_zero


[False  True False]


np.int64(1)

In [ ]:
ndarray = np.array([[1, 1, 1], 
                    [2, 2, 0], 
                    [3, 3, 3]])

# 결측값이 있는 샘플 수를 얻는 방법3
# np.all(): 모든 요소가 0이 아닌 경우 True 반환
all_result = np.all(ndarray != 0, axis=1)
print(all_result)

rows_without_zero = np.count_nonzero(np.all(ndarray != 0, axis=1))
print(rows_without_zero)

print("결측값이 있는 샘플 수:", ndarray.shape[0] - rows_without_zero)


[ True False  True]
2
결측값이 있는 샘플 수: 1


### 결합 함수

In [14]:
# 월별 데이터 합치기
jan = np.array([[1, 100], [2, 200]])
feb = np.array([[3, 300], [4, 400], [5, 500]])
all_data = np.concatenate([jan, feb], axis=0)  # 행 방향 결합
print(all_data)

[[  1 100]
 [  2 200]
 [  3 300]
 [  4 400]
 [  5 500]]


In [16]:
# 피처 추가 (열 방향 결합)
features = np.array([[1, 2], [3, 4]])
new_col  = np.array([[10], [20]])
result = np.concatenate([features, new_col], axis=1)
print(result)

[[ 1  2 10]
 [ 3  4 20]]


### 집계 함수

In [3]:
ndarray = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print("전체 합:", np.sum(ndarray))
print("평균:", np.mean(ndarray))
print("최대:", np.max(ndarray))
print("최소:", np.min(ndarray))
print("표준 편차:", np.std(ndarray))

전체 합: 45
평균: 4.5
최대: 9
최소: 0
표준 편차: 2.8722813232690143
