### 요소별 연산

In [2]:
import numpy as np

ndarray1 = np.array(
    [[6, 7],
     [8, 9]]
)

ndarray2 = np.array(
    [[2, 5],
     [4, 3]]
)

result = ndarray1 * ndarray2
print(result)
print()

result = ndarray1 / ndarray2
print(result)


[[12 35]
 [32 27]]

[[3.  1.4]
 [2.  3. ]]


### 브로드케스팅

In [2]:
import numpy as np

ndarray = np.array(
    [[100, 230],
     [50, 150]]
)

result = ndarray / np.array(255)
print(result)


[[0.39215686 0.90196078]
 [0.19607843 0.58823529]]


### 점곱 연산

In [4]:
import numpy as np

ndarray1 = np.array([[1, 2, 3],
                     [4, 5, 6]])

ndarray2 = np.array([[1, 2],
                     [3, 4],
                     [5, 6]])

result = ndarray1 @ ndarray2
print(result)
print()
result = np.dot(ndarray1, ndarray2)
print(result)


[[22 28]
 [49 64]]

[[22 28]
 [49 64]]
