In [1]:
import numpy as np  # 넘파이 라이브러리 임포트

기본 인덱싱

In [2]:
ndarray = np.array(
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]]
)
print("ndarray[1]:", ndarray[1])
print("ndarray[1, 2]:", ndarray[1, 2])
print("ndarray[1, -1]:", ndarray[1, -1])

ndarray[1]: [5 6 7 8 9]
ndarray[1, 2]: 7
ndarray[1, -1]: 9


In [ ]:
ndarray = np.array(
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]]
)
print("ndarray[1][3]:", ndarray[1, 3])
print("ndarray[1][3]:", ndarray[1][3])

ndarray[1][3]: 8
ndarray[1][3]: 8


인덱스 배열을 이용한 인덱싱

In [4]:
ndarray = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
result = ndarray[
    np.array([2, 4, 7])
]
print(result, type(result))

[12 14 17] <class 'numpy.ndarray'>


In [5]:
ndarray = np.array(
    [[0, 10, 20, 30],
     [1, 11, 21, 31],
     [2, 12, 22, 32],
     [3, 13, 23, 33],
     [4, 14, 24, 34],
     [5, 15, 25, 35],
     [6, 16, 26, 36],
     [7, 17, 27, 37],
     [8, 18, 28, 38],
     [9, 19, 29, 39]]
)

print(ndarray[
    np.array([i for i in range(ndarray.shape[0]) if i%2==0])
    # np.array([0, 2, 4, 6, 8])
])

[[ 0 10 20 30]
 [ 2 12 22 32]
 [ 4 14 24 34]
 [ 6 16 26 36]
 [ 8 18 28 38]]


불리언 배열을 이용한 인덱싱

In [6]:
ndarray = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
condition = (ndarray % 3) == 0
print(condition)
print(ndarray[condition])


[False False  True False False  True False False  True False]
[12 15 18]
